### ISSUE TITLE
Rx.rb or RxRuby

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxRuby#27]
Should the project name be RxRuby or Rx.rb?

It seems the convention is Rx{Lang} such as Rx{JS}, Rx{.Net}, Rx{Java}, Rx{Scala} etc.

I think RxRuby is clearer and matches the naming convention.

**Comment by igneus** [comment]
Please consider ruby gem naming conventions: http://guides.rubygems.org/name-your-gem/

Rx.rb or RxRuby, neither is a good name for a ruby gem. Uppercase letters and dots are not welcome in gem names. rxrb, rxruby, rx_rb, rx_ruby or similar would be much more convenient.

**Comment by igneus** [comment]
Also, right now the gem's "require name" **rx** (name of the file used to require all the library's code) collides with an [already existing gem](https://rubygems.org/gems/rx)

**Comment by witlessbird** [comment]
Any chance this is going to be resolved? Would be great to have a published gem... FWIW any of the names suggested by @igneus would work...

**Comment by witlessbird** [comment]
@mattpodwysocki, @benjchristensen let me know if you need a hand with anything that would speed up publishing of the gem...

**Comment by witlessbird** [comment]
There also appears to be a failure in the last build executed by travis, but it appears to be a transient one,  re-running the build should fix it.

**Comment by witlessbird** [comment]
@mattpodwysocki, @benjchristensen: ping?

**Comment by minamimonji** [comment]
@mattpodwysocki, @benjchristensen 
To summarize above, the followings could be conclusions. 

project name:  **RxRuby**
gem name: **rx_ruby**
main file: **lib/rx_ruby.rb**
main dir: **lib/rx_ruby**
main module: **RxRuby**

any suggestions?

**Comment by witlessbird** [comment]
Looks good to me.

**Comment by benjchristensen** [comment]
That all sounds good. If you're interested in taking ownership of this project I can get you setup.

**Comment by minamimonji** [comment]
@benjchristensen
Sure, I am!
