### ISSUE TITLE
Document how to run the examples

### ISSUE THREAD

**Issue by jfaerman** [ReactiveX/RxRuby#61]
I could not find how to run this repository examples. Here is my shot at it:
```
$ pwd
/Users/faermanj/Dev/rx.rb/examples
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ ruby create.rb 
create.rb:4:in `<main>': uninitialized constant RX::Observable (NameError)
```

**Comment by minamimonji** [comment]
I run them by following way:

```
$ pwd
/path/to/rx.rb/examples
$ ruby -I../lib/ create.rb
# the -I<direcotry> option specifies $LOAD_PATH directory
Next: 42
Completed
disposed
Next: 42
Completed
dispose
```
Is this what you want to do?

**Comment by jfaerman** [comment]
Exactly, this works! Could not load the gem properly tough...
Anyway, i'll read through them and add some docs, thanks a lot!

**Comment by minamimonji** [comment]
@jfaerman, @mattpodwysocki 
This issue is kinda outdated.
Could you get it closed?
