### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by mattdharmon** [ReactiveX/RxRuby#70]
I was kind of wondering the status of development on this project since I am seeing a fair amount of activity on RX JS and the what not.

I am also wondering if this will be published on rubygems for a tryout.

**Comment by jeanlescure** [comment]
Ping for status. One of my projects is interested in implementing this library.

**Comment by pinyin** [comment]
+1

**Comment by ms-ati** [comment]
+1

**Comment by lerencao** [comment]
++1

It hasn't been updated for a while.

**Comment by shlomizadok** [comment]
rubygems, please :question:

**Comment by witlessbird** [comment]
@minamimonji: any chance you could release a gem?

**Comment by shlomizadok** [comment]
+1

**Comment by minamimonji** [comment]
Will be working on it in a next few days. Need to edit the gemspec to clarify the licensing before publishing to the rubygems.org

**Comment by witlessbird** [comment]
Awesome. Will be happy to help should you need any assistance.

**Comment by shlomizadok** [comment]
@minamimonji Thanks! :100:

**Comment by minamimonji** [comment]
rx_ruby v0.0.2 is now on the rubygems.org!
You can try it out.
https://rubygems.org/gems/rx_ruby

**Comment by shlomizadok** [comment]
@minamimonji Thank you so much!

**Comment by wy193777** [comment]
Actively developing? Haven't been updated for 8 month.

**Comment by csjune** [comment]
See https://github.com/ReactiveX/RxRuby/issues/95#issuecomment-270643869
