### ISSUE TITLE
The gem name will be "rx" from v0.0.3

### ISSUE THREAD

**Issue by minamimonji** [ReactiveX/RxRuby#85]
We have renamed the project name from Rx.rb to RxRuby and the gem name Rx.rb to rx_ruby on #27.   We have chosen "rx_ruby" because "rx" has been taken by other project(https://github.com/headius/rx). However I feel uncomfortable with `*_ruby` because I know it is RUBY(why do we have to say ruby in the ruby module?) and writing `require 'rx'` and `Rx::Observable` are much simpler.

I asked the author of the "rx"(https://github.com/headius/rx) to give us the gem name "rx". Thanksfully, he accepted my request. Thank you, @headius!

RxRuby gem is now on https://rubygems.org/gems/rx. Note that the module name and dir name are still rx_ruby as of v0.0.2. We are going to release v0.0.3 with following structure.
project name: **RxRuby** 
gem name: **rx**
main file: **lib/rx.rb**
main dir: **lib/rx**
main module: **Rx**

Since we have not had enough time to add functionalities to RxRuby for a long time, Pull Requests are always welcome like following.
- Adding tests to existing operators.
- Porting operators, schedulers from Rx implemented in other languages.

@mattpodwysocki @benjchristensen any comments on this?

**Comment by headius** [comment]
:+1: glad I could help.
